set -g status off
set -g prefix C-q
unbind-key C-b
set -g escape-time 0
set -g default-terminal "xterm-256color"
set -g history-limit 200000
set -g mouse off
set -g focus-events on
set -g allow-passthrough on
set -ga terminal-overrides ",xterm-256color:Tc:smcup@:rmcup@"
